services:
  - type: web
    name: scraping-service
    runtime: docker
    plan: starter
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    scaling:
      minInstances: 1
      maxInstances: 1
    autoDeploy: true
